"""
providers/storage/base.py — The interface every storage backend implements.

Uploads are *chunked*: begin_upload() reserves space, write_chunk() writes one
piece at its byte offset (pieces may arrive in any order, and may be re-sent),
complete_upload() makes the file visible under its key, abort_upload() throws
it away. This maps one-to-one onto S3 / Cloudflare R2 multipart uploads, so a
cloud provider can be added later without changing the API or the services.

Keys are generated by the server (never taken from a client), e.g.
    videos/<video id>/<random>.mp4
    thumbnails/<video id>/<random>.jpg
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional


class StorageError(Exception):
    """A backend failure (disk full, permission denied, network, ...)."""


class StorageProvider(ABC):
    #: Name used in STORAGE_PROVIDER.
    name: str = "base"

    # ── Chunked uploads (videos) ─────────────────────────────────────────────

    @abstractmethod
    async def begin_upload(self, key: str, size: int) -> None:
        """Prepare to receive `size` bytes for `key`."""

    @abstractmethod
    async def write_chunk(self, key: str, offset: int, data: bytes) -> None:
        """Write `data` at byte `offset` of the in-progress upload. Idempotent."""

    @abstractmethod
    async def read_upload_head(self, key: str, length: int) -> bytes:
        """The first `length` bytes of the in-progress upload (format sniffing)."""

    @abstractmethod
    async def complete_upload(self, key: str) -> None:
        """Make the uploaded bytes available under `key`."""

    @abstractmethod
    async def abort_upload(self, key: str) -> None:
        """Discard an in-progress upload. Safe to call when there is none."""

    # ── Whole objects (thumbnails) ───────────────────────────────────────────

    @abstractmethod
    async def put(self, key: str, data: bytes, content_type: str) -> None:
        """Store a small object in one go."""

    @abstractmethod
    async def delete(self, key: str) -> None:
        """Delete an object. Safe to call when it doesn't exist."""

    @abstractmethod
    async def exists(self, key: str) -> bool: ...

    @abstractmethod
    async def put_file(self, key: str, src: Path, content_type: str) -> None:
        """Store a finished local file under `key` (the source file is consumed)."""

    @abstractmethod
    async def delete_prefix(self, prefix: str) -> None:
        """Delete every object under `prefix` (e.g. a document's rendered pages)."""

    def staging_dir(self) -> Path:
        """Where to write temporary files before put_file()."""
        import tempfile

        return Path(tempfile.gettempdir())

    # ── Serving & capacity ───────────────────────────────────────────────────

    def local_path(self, key: str) -> Optional[Path]:
        """A filesystem path the API can serve directly, or None for cloud
        backends (which hand out their own signed URLs instead)."""
        return None

    def free_bytes(self) -> Optional[int]:
        """Free space available to this backend, or None if effectively unlimited."""
        return None

    def health(self) -> str:
        return "ok"
